#!/usr/bin/env python
import server
import files
import args
import classification

# load commandline args
opts = args.load()

# Building Flask App
app = server.load()

# Load Submodules
classification.load(opts)

# Register Submodule Routes
files.register(app, opts)
classification.register(app, opts)



if __name__ == "__main__":
    print("""
   _____                                                      
  / ____|                                                     
 | |     ___  _ __ _ __  _   _ ___  __ _ _   _ _ __ _   _ ___ 
 | |    / _ \| '__| '_ \| | | / __|/ _` | | | | '__| | | / __|
 | |___| (_) | |  | |_) | |_| \__ \ (_| | |_| | |  | |_| \__ \\
  \_____\___/|_|  | .__/ \__,_|___/\__,_|\__,_|_|   \__,_|___/
                  | |                                         
                  |_|                                         
    """)
    print("Version 0.2")
    app.run(host=opts.host, port=int(opts.port), debug=opts.debug)
